---
# tasks file for nginx
- name: update
  apt: update_cache=yes
- name: install nginx
  apt: name=nginx state=present
- name: suppression default
  file: path=/etc/nginx/sites-available/default state=absent
- name: installation php
  include: php.yml
- name: configuration des sites
  include: sites.yml
  with_items:
    - "{{ domains }}"