---
# tasks file for web
- name: update
  apt: update_cache=yes
- name: install nginx
  apt: name=nginx state=present
- name: Start
  service: name=nginx state=started
- name: installation php
  include: php.yml
- name: installation mysql
  include: mysql.yml
- name: create database and user
  include: data.yml